### ISSUE TITLE
Ability to manually set CI info for testing

### ISSUE THREAD

**Issue by charlespierce** [sagiegurari/ci_info#12]
**Feature Description**
We're looking at using this crate to control the output of a CLI tool, and would like to be able to _test_ that behavior, both for when our tool is run in CI and on user machines. However, all of our tests themselves run in CI, so `ci_info` always (correctly) detects a CI environment, meaning we can't easily test the "outside of CI" output.

**Describe the solution you'd like**
A method to force a set of CI info to be returned by the `get()` function, usable in test so that we can force the behavior we want and test our output. Alternatively, a method to clear all of the environment variables that `ci_info` checks, so that we can simulate a non-CI environment.

**Code Sample**
```rust
use ci_info::{self, types::CiInfo};
ci_info::set(CiInfo::new());
ci_info::is_ci(); // Will return false, regardless of the actual environment variables
```

**Comment by sagiegurari** [comment]
that's a really interesting idea.
i actually have the code in my tests of this crate.
i could expose it differently, and we can see if it helps or not :)

**Comment by sagiegurari** [comment]
@charlespierce this is now supported via new mock_ci function.
example:

```rust
use ci_info;
use ci_info::types::{CiInfo, Vendor};

fn main() {
    // create the CI info manually
    let mut mock_info = CiInfo::new();
    mock_info.vendor = Some(Vendor::TravisCI);
    mock_info.ci = true;
    mock_info.pr = Some(true);
    mock_info.branch_name = Some("dev_branch".to_string());

    // mock environment
    ci_info::mock_ci(&mock_info);

    let info = ci_info::get();

    assert!(info.ci);
    assert!(info.pr.unwrap());
    assert_eq!(info.vendor.unwrap(), Vendor::TravisCI);
    assert_eq!(info.name.unwrap(), "Travis CI");
    assert_eq!(info.branch_name.unwrap(), "dev_branch");

    // clear CI environment
    mock_info = CiInfo::new();
    ci_info::mock_ci(&mock_info);

    let info = ci_info::get();

    assert!(!info.ci);
}
```

**Comment by charlespierce** [comment]
@sagiegurari That looks perfect! Thanks for implementing it so quickly!
