### ISSUE TITLE
Feature request: bring back serde!

### ISSUE THREAD

**Issue by EverlastingBugstopper** [sagiegurari/ci_info#19]
### Feature Description
Hi! I'm currently using the `[serde-1]` feature from versions <= v0.12 and would _love_ to have it continue to be supported under a feature flag (maybe just `serde`?).

If it's really a problem I can always use serde's [remote derive](https://serde.rs/remote-derive.html) but it's just much more convenient to have this provided in the library itself!

Thanks so much for your time. If you decide it's OK to keep I'm very happy to submit a PR!

**Comment by sagiegurari** [comment]
i removed it because i didn't think it was used and its original usage was never really necessary.
i can add it back, but curious why serialization is needed here?

**Comment by sagiegurari** [comment]
closing due to lack of feedback.

**Comment by EverlastingBugstopper** [comment]
Hey sorry! I was on vacation the past few weeks.

The reason that we're using the `serde-1` feature currently is because we are serializing the information from the `CiInfo` struct into JSON which we are then sending to a REST API. I think that it would be a fairly common use case for consumers of this API.

**Comment by sagiegurari** [comment]
@EverlastingBugstopper  I've added it back. Release as version 0.14.0

**Comment by EverlastingBugstopper** [comment]
Amazing!! Thank you so much 😄
