### ISSUE TITLE
Detect PRs

### ISSUE THREAD

**Issue by mikaelmello** [sagiegurari/ci_info#2]
**Features Description**

It would be nice if you added PR detection, [ci-info has information on env vars regarding PRs](https://github.com/watson/ci-info/blob/master/vendors.json)

**Describe the solution you'd like**

A nice API that checks whether the PR can be detected and if it is detected.

**Comment by sagiegurari** [comment]
will do. thanks!!!!

**Comment by sagiegurari** [comment]
PR flag (and few other changes as well) are now pushed.
since this is a breaking change (not the pr but the other stuff that i pushed) i will be a new minor version.
Thanks for the suggestion!!!

**Comment by sagiegurari** [comment]
published in version 0.4.0

**Comment by mikaelmello** [comment]
Great, thanks for the fast work!
